version: "3"
services:
  jira:
    image: atlassian/jira-software:latest
    ports:
      - "8080:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://${DB_HOST}:5432/jiradb
      - ATL_DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=jiradb
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=${DB_PASSWORD}
